### ISSUE TITLE
Unused self.out_projection

### ISSUE THREAD

**Issue by SolomidHero** [sooftware/Attention-Implementation#1]
In 2 places:

https://github.com/sooftware/attentions/blob/d6a6b12b8a2b473e5a23e37a13c9547f00f8ffb4/attentions.py#L52

https://github.com/sooftware/attentions/blob/d6a6b12b8a2b473e5a23e37a13c9547f00f8ffb4/attentions.py#L192

**Comment by sooftware** [comment]
I reflected it. Thank you.
